baseURL = "https://clever-moomin.github.io/remote/"
languageCode = "ja-jp"
DefaultContentLanguage = "ja"
title = "chibo"
theme = "anatole"
#summary（TOPページなどで表示されている記事の概要）のテキスト文字数を決めることができます。
summarylength = 0
HasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Chibo/ちぼ"
author = "chibo blog"
#copyright = "chibo"
description = "Web開発やDX支援や音楽を教えたりして生きてます"
#メモ　I am what I am.
profilePicture = "images/b1.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
disableThemeSwitcher = true # Theme switcher is enabled by default

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/LaravelCat"

[[params.socialIcons]]
icon = "fab fa-laravel"
title = "GitHub"
url = "https://clever-moomin.github.io/remote/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://clever-moomin.github.io/remote/"

[[params.socialIcons]]
icon = "fas fa-headphones"
title = "e-mail"
url = "https://clever-moomin.github.io/remote/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"


publishDir = "docs"
